/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "switch_intr.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
Orange LED will blink when switch is pressed -- Any Optimization Level
As flag is declared volatile.
*/

int main(void)
{
	SystemInit();
	SwitchInit();
	LedInit(LED_ORANGE_PIN);
	LedInit(LED_RED_PIN);
    LedInit(LED_BLUE_PIN);
	LedInit(LED_GREEN_PIN);

	while(1)
	{
		if (SwitchExtiFlag) {
			while (!(GPIOA->IDR & (1 << SWITCH_PIN))) {
			}
			LedBlink(LED_RED_PIN, 1000);
			while (!(GPIOA->IDR & (1 << SWITCH_PIN))) {

			            }


			            LedBlink(LED_BLUE_PIN, 1000);

			            while (!(GPIOA->IDR & (1 << SWITCH_PIN))) {

			            }
			            LedBlink(LED_GREEN_PIN, 1000);
			          //  LedBlink(LED_ORANGE_PIN, 1000);
		             	//LedBlink(LED_RED_PIN, 1000);
			            //LedBlink(LED_GREEN_PIN, 1000);
			            //LedBlink(LED_BLUE_PIN, 1000);
			            SwitchExtiFlag = 0;

		// if switch is pressed blink orange led
	//	while(SwitchExtiFlag == 0)
      //  LedBlink(LED_ORANGE_PIN, 1000);
		//SwitchExtiFlag = 0;


		}

	}
	return 0;
}
























